### ISSUE TITLE
[meta] D3D12 portability concerns

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Portability#8]
(this list is to be edited)
- [ ] unnormalized sampler coordinates - https://github.com/gfx-rs/gfx/issues/2883
- [x] D3D12 command allocator (analogue of `VkDescriptorPool`) only allows one command list to be recorded at a time. I thought that we could add a flag for that, since most users don't get affected by this limitation. In the end, we implemented a scheme that dynamically juggles the allocators to avoid this problem in https://github.com/gfx-rs/gfx/pull/3393.
- [x] sampler heap limitation of 2048. This prevents users to create descriptor pools with more than 2048 samplers - https://github.com/gfx-rs/gfx/issues/2652
- [ ] some of the pipeline states (that can be static or dynamic in Vulkan) are strictly static in D3D12. Namely, depth bias and stencil read/write masks. I suggest we have this restriction encoded in the portability spec.
- [ ] unable to reset a resource state with `VK_IMAGE_LAYOUT_UNDEFINED`
